name: Playwright Tests
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21
      - name: Download drivers
        shell: bash
        run: scripts/download_driver.sh
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run: mvn test --no-transfer-progress --fail-at-end
        env:
          BROWSER: ${{ matrix.browser }}
      - name: Test Spring Boot Starter
        shell: bash
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          cd tools/test-spring-boot-starter
          mvn package -D skipTests --no-transfer-progress
          java -jar target/test-spring-boot*.jar